name: java-kubernetes-pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-java:
    name: Build & Deploy Java App
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # ✅ Setup Java + Maven cache
      - name: Set up JDK 11 with Maven cache
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      # ✅ Build ProductCatalogue
      - name: Build ProductCatalogue
        working-directory: productcatalogue
        run: mvn clean install -B

      # ✅ Build Shopfront
      - name: Build Shopfront
        working-directory: shopfront
        run: mvn clean install -B

      # ✅ Build StockManager
      - name: Build StockManager
        working-directory: stockmanager
        run: mvn clean install -B

      # ✅ Log in to GitHub Container Registry (use GHCR_PAT secret)
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # ✅ Build Docker images for each service
      - name: Build Docker images
        run: |
          docker build -t ghcr.io/af1nzr/productcatalogue:latest -f productcatalogue/Dockerfile .
          docker build -t ghcr.io/af1nzr/shopfront:latest -f shopfront/Dockerfile .
          docker build -t ghcr.io/af1nzr/stockmanager:latest -f stockmanager/Dockerfile .

      # ✅ Push Docker images to GitHub Container Registry
      - name: Push Docker images
        run: |
          docker push ghcr.io/af1nzr/productcatalogue:latest
          docker push ghcr.io/af1nzr/shopfront:latest
          docker push ghcr.io/af1nzr/stockmanager:latest

      # ✅ Setup kubeconfig (secret stored in GitHub Actions)
      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig.yaml
          mkdir -p ~/.kube
          mv kubeconfig.yaml ~/.kube/config

      # ✅ Create/update Kubernetes secret for pulling GHCR private images
      - name: Create GHCR secret in Kubernetes
        run: |
          kubectl delete secret ghcr-secret --ignore-not-found
          kubectl create secret docker-registry ghcr-secret \
            --docker-server=ghcr.io \
            --docker-username=af1nzr \
            --docker-password=${{ secrets.GHCR_PAT }} \
            --docker-email=you@example.com

      # ✅ Deploy services to Kubernetes cluster
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/productcatalogue-service.yaml
          kubectl apply -f kubernetes/shopfront-service.yaml
          kubectl apply -f kubernetes/stockmanager-service.yaml

      # ✅ Wait for deployments to roll out
      - name: Wait for deployments
        run: |
          kubectl rollout status deployment/productcatalogue --timeout=120s
          kubectl rollout status deployment/shopfront --timeout=120s
          kubectl rollout status deployment/stockmanager --timeout=120s

      # ✅ Verify pods & services
      - name: Verify deployments & services
        run: |
          kubectl get pods -l app=productcatalogue
          kubectl get pods -l app=shopfront
          kubectl get pods -l app=stockmanager
          kubectl get services productcatalogue shopfront stockmanager
