name: java-kubernetes-pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-java:
    name: Build & Deploy Java App
    runs-on: ubuntu-latest

    steps:
      # ✅ 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # ✅ 2. Setup Java + Maven cache
      - name: Set up JDK 11 with Maven cache
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      # ✅ 3. Build ProductCatalogue JAR
      - name: Build ProductCatalogue
        working-directory: productcatalogue
        run: mvn clean package -DskipTests

      # ✅ 4. Build Shopfront JAR
      - name: Build Shopfront
        working-directory: shopfront
        run: mvn clean package -DskipTests

      # ✅ 5. Build StockManager JAR
      - name: Build StockManager
        working-directory: stockmanager
        run: mvn clean package -DskipTests

      # ✅ 6. Log in to GitHub Container Registry (GHCR_PAT secret required)
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # ✅ 7. Build Docker images (build each service from its own folder!)
      - name: Build Docker images
        run: |
          docker build \
            -t ghcr.io/af1nzr/productcatalogue:latest \
            productcatalogue
          
          docker build \
            -t ghcr.io/af1nzr/shopfront:latest \
            shopfront
          
          docker build \
            -t ghcr.io/af1nzr/stockmanager:latest \
            stockmanager

      # ✅ 8. Push Docker images to GHCR
      - name: Push Docker images
        run: |
          docker push ghcr.io/af1nzr/productcatalogue:latest
          docker push ghcr.io/af1nzr/shopfront:latest
          docker push ghcr.io/af1nzr/stockmanager:latest

      # ✅ 9. Setup kubeconfig from secret
      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig.yaml
          mkdir -p ~/.kube
          mv kubeconfig.yaml ~/.kube/config
